apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- https://github.com/statisticsnorway/atlantis-bootstrap/kubernetes-manifests/atlantis-statefulset?ref=main
patchesStrategicMerge:
- ingress.yaml
- atlantis-statefulset.yaml
secretGenerator:
- name: atlantis
  files:
  - gh-webhook-secret
  - gh-key-file
generatorOptions:
  disableNameSuffixHash: true
